module.exports = {
  presets: [
    {
      theme: {
        extend: {
          screens: {
            xs: '480px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1400px',
          },
          colors: {
            current: 'currentColor',
            transparent: 'transparent',
            black: '#000',
            white: '#fff',
            orange: {
              '50': '#fff7ed',
              '100': '#ffedd5',
              '200': '#fed7aa',
              '300': '#fdba74',
              '400': '#fb923c',
              '500': '#f97316',
              '600': '#ea580c',
              '700': '#c2410c',
              '800': '#9a3412',
              '900': '#7c2d12',
            },
            gray: {
              '50': '#EFF0F3',
              '100': '#E5E6EB',
              '200': '#D7D9DF',
              '300': '#BBBDC5',
              '400': '#A4A5AD',
              '500': '#787a88',
              '600': '#626474',
              '700': '#4b4e60',
              '800': '#35384c',
              '900': '#16192B',
            },
            teal: {
              '50': '#ecf5f3',
              '100': '#c6e2db',
              '200': '#a0cfc4',
              '300': '#7abbac',
              '400': '#54a894',
              '500': '#429f89',
              '600': '#347f6d',
              '700': '#275f52',
              '800': '#1a3f36',
              '900': '#00473F',
            },
            indigo: {
              '50': '#e5e7ee',
              '100': '#ccd0de',
              '200': '#b2b8cd',
              '300': '#99a1bd',
              '400': '#7f89ad',
              '500': '#66729c',
              '600': '#4c5a8c',
              '700': '#32427b',
              '800': '#192b6b',
              '900': '#00145b',
            },
            yellow: {
              '50': '#fff6e6',
              '100': '#ffeecc',
              '200': '#ffe5b3',
              '300': '#ffdc99',
              '400': '#FFD480',
              '500': '#FFCB66',
              '600': '#ffc24d',
              '700': '#ffb933',
              '800': '#ffb11a',
              '900': '#ffa800',
            },
            blueGray: {
              '50': '#e9ebfa',
              '100': '#d4d7f4',
              '200': '#bec3ef',
              '300': '#a9afe9',
              '400': '#939be4',
              '500': '#7d87df',
              '600': '#6873d9',
              '700': '#525fd4',
              '800': '#3d4bce',
              '900': '#2737c9',
            },
            blue: {
              '50': '#cfdff7',
              '100': '#b8cff3',
              '200': '#89b0eb',
              '300': '#71a0e7',
              '400': '#4281df',
              '500': '#1362d8',
              '600': '#0d4497',
              '700': '#09316c',
              '800': '#051d40',
              '900': '#00145B',
            },
            darkBlue: {
              '50': '#e6e6e9',
              '100': '#cdced4',
              '200': '#b4b6bf',
              '300': '#9b9da9',
              '400': '#838594',
              '500': '#6a6d7f',
              '600': '#515469',
              '700': '#383c54',
              '800': '#1f243f',
              '900': '#070C2A',
            },
            violet: {
              '50': '#F7F0FF',
              '100': '#ECD9FF',
              '200': '#E0C4FC',
              '300': '#CFA6F8',
              '400': '#b680ed',
              '500': '#a766e9',
              '600': '#994de6',
              '700': '#8a33e2',
              '800': '#7c1adf',
              '900': '#6400C9',
            },
            purple: {
              '50': '#eccff1',
              '100': '#daa0e3',
              '200': '#c771d6',
              '300': '#be59cf',
              '400': '#ac2ac1',
              '500': '#a313bb',
              '600': '#9211a8',
              '700': '#820f95',
              '800': '#610b70',
              '900': '#41074a',
            },
            red: {
              '50': '#f9e6e6',
              '100': '#FFDEDE',
              '200': '#FBC2C2',
              '300': '#F5A5A5',
              '400': '#EF8A8A',
              '500': '#EA6D6D',
              '600': '#E25454',
              '700': '#DD3838',
              '800': '#D62323',
              '900': '#C30000',
            },
            sky: {
              '50': '#e6f8fc',
              '100': '#ccf1fa',
              '200': '#b3ebf7',
              '300': '#99e4f4',
              '400': '#80ddf2',
              '500': '#66d6ef',
              '600': '#4dcfec',
              '700': '#33c9e9',
              '800': '#1ac2e7',
              '900': '#00bbe4',
            },
            green: {
              '50': '#e6f7f1',
              '100': '#ccefe2',
              '200': '#b3e6d4',
              '300': '#99dec5',
              '400': '#80d6b7',
              '500': '#66cea9',
              '600': '#4dc69a',
              '700': '#33bd8c',
              '800': '#1ab57d',
              '900': '#00ad6f',
            },
          },
          spacing: {
            '0': '0px',
            '1': '0.25rem',
            '2': '0.5rem',
            '3': '0.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '7': '1.75rem',
            '8': '2rem',
            '9': '2.25rem',
            '10': '2.5rem',
            '11': '2.75rem',
            '12': '3rem',
            '14': '3.5rem',
            '16': '4rem',
            '18': '4.5rem',
            '20': '5rem',
            '24': '6rem',
            '26': '6.5rem',
            '28': '7rem',
            '32': '8rem',
            '36': '9rem',
            '40': '10rem',
            '44': '11rem',
            '48': '12rem',
            '52': '13rem',
            '56': '14rem',
            '60': '15rem',
            '64': '16rem',
            '72': '18rem',
            '74': '18.5rem',
            '80': '20rem',
            '96': '24rem',
            '100': '25rem',
            '112': '28rem',
            '116': '29rem',
            '128': '32rem',
            '135': '33.75rem',
            '148': '37rem',
            '160': '40rem',
            '170': '42.5rem',
            '186': '46.5rem',
            '235': '58.75rem',
            '470': '117.5rem',
            px: '1px',
            '0.5': '0.125rem',
            '1.5': '0.375rem',
            '2.5': '0.625rem',
            '3.5': '0.875rem',
          },
          animation: {
            none: 'none',
            spin: 'spin 1s linear infinite',
            ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
            pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            bounce: 'bounce 1s infinite',
          },
          backdropBlur: (theme) => theme('blur'),
          backdropBrightness: (theme) => theme('brightness'),
          backdropContrast: (theme) => theme('contrast'),
          backdropGrayscale: (theme) => theme('grayscale'),
          backdropHueRotate: (theme) => theme('hueRotate'),
          backdropInvert: (theme) => theme('invert'),
          backdropOpacity: (theme) => theme('opacity'),
          backdropSaturate: (theme) => theme('saturate'),
          backdropSepia: (theme) => theme('sepia'),
          backgroundColor: (theme) => ({
            ...theme('colors'),
            body: '#070C2A',
          }),
          backgroundImage: {
            none: 'none',
            'gradient-to-t':
              'linear-gradient(to top, var(--tw-gradient-stops))',
            'gradient-to-tr':
              'linear-gradient(to top right, var(--tw-gradient-stops))',
            'gradient-to-r':
              'linear-gradient(to right, var(--tw-gradient-stops))',
            'gradient-to-br':
              'linear-gradient(to bottom right, var(--tw-gradient-stops))',
            'gradient-to-b':
              'linear-gradient(to bottom, var(--tw-gradient-stops))',
            'gradient-to-bl':
              'linear-gradient(to bottom left, var(--tw-gradient-stops))',
            'gradient-to-l':
              'linear-gradient(to left, var(--tw-gradient-stops))',
            'gradient-to-tl':
              'linear-gradient(to top left, var(--tw-gradient-stops))',
            radial: 'radial-gradient(var(--tw-gradient-stops))',
            'gradient-violet-blue':
              'linear-gradient(90deg, #826FFF 0%, #511CFF 48.96%, #00D1FF 100%)',
            'gradient-tag':
              'linear-gradient(158deg, #826FFF 1.14%, #511CFF 51.87%, #00D1FF 104.76%)',
          },
          backgroundOpacity: (theme) => theme('opacity'),
          backgroundPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
          },
          backgroundSize: {
            auto: 'auto',
            cover: 'cover',
            contain: 'contain',
          },
          blur: {
            '0': '0',
            none: '0',
            sm: '4px',
            DEFAULT: '8px',
            md: '12px',
            lg: '16px',
            xl: '24px',
            '2xl': '40px',
            '3xl': '64px',
          },
          brightness: {
            '0': '0',
            '50': '.5',
            '75': '.75',
            '90': '.9',
            '95': '.95',
            '100': '1',
            '105': '1.05',
            '110': '1.1',
            '125': '1.25',
            '150': '1.5',
            '200': '2',
          },
          borderColor: (theme) => ({
            ...theme('colors'),
            DEFAULT: '#e5e7eb',
          }),
          borderOpacity: (theme) => theme('opacity'),
          borderRadius: {
            none: '0',
            sm: '0.125rem',
            DEFAULT: '0.25rem',
            md: '0.375rem',
            lg: '0.5rem',
            xl: '0.75rem',
            '2xl': '1rem',
            '3xl': '1.25rem',
            '4xl': '1.875rem',
            '5xl': '5rem',
            full: '9999px',
          },
          borderWidth: {
            '0': '0',
            '2': '2px',
            '3': '3px',
            '4': '4px',
            '8': '8px',
            DEFAULT: '1px',
          },
          boxShadow: {
            sm: '0px 1px 2px 0px rgba(156, 163, 175, 0.30)',
            DEFAULT:
              '0px 6px 10px -2px rgba(85, 105, 135, 0.04), 0px 2px 4px -2px rgba(85, 105, 135, 0.02)',
            md: '0px 12px 16px -4px rgba(85, 105, 135, 0.04), 0px 4px 6px -2px rgba(85, 105, 135, 0.02)',
            lg: '0px 20px 24px -4px rgba(85, 105, 135, 0.04), 0px 8px 8px -4px rgba(85, 105, 135, 0.02)',
            xl: '0px 2px 4px -2px rgba(42, 51, 66, 0.03), 0px 6px 10px -2px rgba(42, 51, 66, 0.06)',
            '2xl': '0px 32px 64px -12px rgba(85, 105, 135, 0.08)',
            '3xl': '0px 0px 8px 0px rgba(255, 255, 255, 0.20)',
            '4xl': '0px 0px 8px 0px rgba(209, 213, 219, 0.50)',
            'box-violet': '-2px -2px 1px rgba(83,28,199,.5)',
            'box-orange': '-2px -2px 1px rgba(199,79,28,.5)',
            'box-green': '-2px -2px 1px rgba(45,133,75,.5)',
            inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
            none: 'none',
          },
          caretColor: (theme) => theme('colors'),
          contrast: {
            '0': '0',
            '50': '.5',
            '75': '.75',
            '100': '1',
            '125': '1.25',
            '150': '1.5',
            '200': '2',
          },
          container: [],
          cursor: {
            auto: 'auto',
            DEFAULT: 'default',
            pointer: 'pointer',
            wait: 'wait',
            text: 'text',
            move: 'move',
            'not-allowed': 'not-allowed',
          },
          divideColor: (theme) => theme('borderColor'),
          divideOpacity: (theme) => theme('borderOpacity'),
          divideWidth: (theme) => theme('borderWidth'),
          dropShadow: {
            sm: '0 1px 1px rgba(0,0,0,0.05)',
            DEFAULT: [
              '0 1px 2px rgba(0, 0, 0, 0.1)',
              '0 1px 1px rgba(0, 0, 0, 0.06)',
            ],
            md: [
              '0 4px 3px rgba(0, 0, 0, 0.07)',
              '0 2px 2px rgba(0, 0, 0, 0.06)',
            ],
            lg: [
              '0 10px 8px rgba(0, 0, 0, 0.04)',
              '0 4px 3px rgba(0, 0, 0, 0.1)',
            ],
            xl: [
              '0 20px 13px rgba(0, 0, 0, 0.03)',
              '0 8px 5px rgba(0, 0, 0, 0.08)',
            ],
            '2xl': '0 25px 25px rgba(0, 0, 0, 0.15)',
            none: '0 0 #0000',
          },
          fill: {
            current: 'currentColor',
          },
          grayscale: {
            '0': '0',
            DEFAULT: '100%',
          },
          hueRotate: {
            '0': '0deg',
            '15': '15deg',
            '30': '30deg',
            '60': '60deg',
            '90': '90deg',
            '180': '180deg',
            '-180': '-180deg',
            '-90': '-90deg',
            '-60': '-60deg',
            '-30': '-30deg',
            '-15': '-15deg',
          },
          invert: {
            '0': '0',
            DEFAULT: '100%',
          },
          flex: {
            '1': '1 1 0%',
            auto: '1 1 auto',
            initial: '0 1 auto',
            none: 'none',
          },
          flexGrow: {
            '0': '0',
            DEFAULT: '1',
          },
          flexShrink: {
            '0': '0',
            DEFAULT: '1',
          },
          fontFamily: {
            body: '"Clash Display", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            heading:
              '"Clash Display", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            sans: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            serif:
              'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
            mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
          },
          fontSize: {
            xs: [
              '0.75rem',
              {
                lineHeight: '1.5',
              },
            ],
            sm: [
              '0.875rem',
              {
                lineHeight: '1.25',
              },
            ],
            base: [
              '1rem',
              {
                lineHeight: '1.5',
              },
            ],
            lg: [
              '1.125rem',
              {
                lineHeight: '1.5',
              },
            ],
            xl: [
              '1.25rem',
              {
                lineHeight: '1.5',
              },
            ],
            '2xl': [
              '1.5rem',
              {
                lineHeight: '1.3',
              },
            ],
            '3xl': [
              '1.875rem',
              {
                lineHeight: '1.3',
              },
            ],
            '4xl': [
              '2.25rem',
              {
                lineHeight: '1.2',
              },
            ],
            '5xl': [
              '3rem',
              {
                lineHeight: '1.25',
              },
            ],
            '6xl': [
              '3.75rem',
              {
                lineHeight: '1.2',
              },
            ],
            '7xl': [
              '4.5rem',
              {
                lineHeight: '1.25',
              },
            ],
            '8xl': [
              '6rem',
              {
                lineHeight: '1.25',
              },
            ],
            '9xl': [
              '10.75rem',
              {
                lineHeight: '1.25',
              },
            ],
          },
          fontWeight: {
            hairline: '100',
            thin: '200',
            light: '300',
            normal: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
            extrabold: '800',
            black: '900',
          },
          gap: (theme) => theme('spacing'),
          gradientColorStops: (theme) => theme('colors'),
          gridAutoColumns: {
            auto: 'auto',
            min: 'min-content',
            max: 'max-content',
            fr: 'minmax(0, 1fr)',
          },
          gridAutoRows: {
            auto: 'auto',
            min: 'min-content',
            max: 'max-content',
            fr: 'minmax(0, 1fr)',
          },
          gridColumn: {
            auto: 'auto',
            'span-1': 'span 1 / span 1',
            'span-2': 'span 2 / span 2',
            'span-3': 'span 3 / span 3',
            'span-4': 'span 4 / span 4',
            'span-5': 'span 5 / span 5',
            'span-6': 'span 6 / span 6',
            'span-7': 'span 7 / span 7',
            'span-8': 'span 8 / span 8',
            'span-9': 'span 9 / span 9',
            'span-10': 'span 10 / span 10',
            'span-11': 'span 11 / span 11',
            'span-12': 'span 12 / span 12',
            'span-full': '1 / -1',
          },
          gridColumnEnd: {
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            '8': '8',
            '9': '9',
            '10': '10',
            '11': '11',
            '12': '12',
            '13': '13',
            auto: 'auto',
          },
          gridColumnStart: {
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            '8': '8',
            '9': '9',
            '10': '10',
            '11': '11',
            '12': '12',
            '13': '13',
            auto: 'auto',
          },
          gridRow: {
            auto: 'auto',
            'span-1': 'span 1 / span 1',
            'span-2': 'span 2 / span 2',
            'span-3': 'span 3 / span 3',
            'span-4': 'span 4 / span 4',
            'span-5': 'span 5 / span 5',
            'span-6': 'span 6 / span 6',
            'span-full': '1 / -1',
          },
          gridRowStart: {
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            auto: 'auto',
          },
          gridRowEnd: {
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            auto: 'auto',
          },
          gridTemplateColumns: {
            '1': 'repeat(1, minmax(0, 1fr))',
            '2': 'repeat(2, minmax(0, 1fr))',
            '3': 'repeat(3, minmax(0, 1fr))',
            '4': 'repeat(4, minmax(0, 1fr))',
            '5': 'repeat(5, minmax(0, 1fr))',
            '6': 'repeat(6, minmax(0, 1fr))',
            '7': 'repeat(7, minmax(0, 1fr))',
            '8': 'repeat(8, minmax(0, 1fr))',
            '9': 'repeat(9, minmax(0, 1fr))',
            '10': 'repeat(10, minmax(0, 1fr))',
            '11': 'repeat(11, minmax(0, 1fr))',
            '12': 'repeat(12, minmax(0, 1fr))',
            none: 'none',
          },
          gridTemplateRows: {
            '1': 'repeat(1, minmax(0, 1fr))',
            '2': 'repeat(2, minmax(0, 1fr))',
            '3': 'repeat(3, minmax(0, 1fr))',
            '4': 'repeat(4, minmax(0, 1fr))',
            '5': 'repeat(5, minmax(0, 1fr))',
            '6': 'repeat(6, minmax(0, 1fr))',
            none: 'none',
          },
          height: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            full: '100%',
            screen: '100vh',
          }),
          inset: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            full: '100%',
            '-1/2': '-50%',
            '-1/3': '-33.333333%',
            '-2/3': '-66.666667%',
            '-1/4': '-25%',
            '-2/4': '-50%',
            '-3/4': '-75%',
            '-full': '-100%',
          }),
          keyframes: {
            spin: {
              to: {
                transform: 'rotate(360deg)',
              },
            },
            ping: {
              '75%, 100%': {
                transform: 'scale(2)',
                opacity: '0',
              },
            },
            pulse: {
              '50%': {
                opacity: '.5',
              },
            },
            bounce: {
              '0%, 100%': {
                transform: 'translateY(-25%)',
                animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
              },
              '50%': {
                transform: 'none',
                animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
              },
            },
          },
          letterSpacing: {
            '10xl': '-4.8px',
            '9xl': '-4px',
            '8xl': '-3.6px',
            '7xl': '-1.86px',
            '6xl': '-1.44px',
            '5xl': '-0.96px',
            '4xl': '-2px',
            '3xl': '-0.64px',
            '2xl': '-0.48px',
            tightest: '-0.05em',
            tighter: '-0.04em',
            tight: '-0.02em',
            normal: '0em',
            wide: '0.025em',
            wider: '0.05em',
            widest: '0.1em',
          },
          lineHeight: {
            '3': '.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '7': '1.75rem',
            '8': '2rem',
            '9': '2.25rem',
            '10': '2.5rem',
            none: '1',
            tight: '1.25',
            snug: '1.375',
            normal: '1.5',
            relaxed: '1.625',
            loose: '2',
          },
          listStyleType: {
            none: 'none',
            disc: 'disc',
            decimal: 'decimal',
          },
          margin: (theme, { negative }) => ({
            auto: 'auto',
            ...theme('spacing'),
            ...negative(theme('spacing')),
          }),
          maxHeight: {
            full: '100%',
            screen: '100vh',
          },
          maxWidth: {
            '0': '0rem',
            none: 'none',
            xs: '20rem',
            sm: '24rem',
            md: '28rem',
            lg: '32rem',
            xl: '36rem',
            '2xl': '42rem',
            '3xl': '48rem',
            '4xl': '50rem',
            '5xl': '56rem',
            '6xl': '63rem',
            '7xl': '72rem',
            '8xl': '76rem',
            full: '100%',
            min: 'min-content',
            max: 'max-content',
            prose: '65ch',
          },
          minHeight: {
            '0': '0',
            full: '100%',
            screen: '100vh',
          },
          minWidth: {
            '0': '0',
            full: '100%',
            min: 'min-content',
            max: 'max-content',
          },
          objectPosition: {
            bottom: 'bottom',
            center: 'center',
            left: 'left',
            'left-bottom': 'left bottom',
            'left-top': 'left top',
            right: 'right',
            'right-bottom': 'right bottom',
            'right-top': 'right top',
            top: 'top',
          },
          opacity: {
            '0': '0',
            '5': '0.05',
            '10': '0.1',
            '20': '0.2',
            '25': '0.25',
            '30': '0.3',
            '40': '0.4',
            '50': '0.5',
            '60': '0.6',
            '70': '0.7',
            '75': '0.75',
            '80': '0.8',
            '90': '0.9',
            '95': '0.95',
            '100': '1',
          },
          order: {
            '1': '1',
            '2': '2',
            '3': '3',
            '4': '4',
            '5': '5',
            '6': '6',
            '7': '7',
            '8': '8',
            '9': '9',
            '10': '10',
            '11': '11',
            '12': '12',
            first: '-9999',
            last: '9999',
            none: '0',
          },
          outline: {
            none: ['2px solid transparent', '2px'],
            white: ['2px dotted white', '2px'],
            black: ['2px dotted black', '2px'],
          },
          padding: (theme) => theme('spacing'),
          placeholderColor: (theme) => theme('colors'),
          placeholderOpacity: (theme) => theme('opacity'),
          ringColor: (theme) => ({
            DEFAULT: theme('colors.blue.500', '#3b82f6'),
            ...theme('colors'),
          }),
          ringOffsetColor: (theme) => theme('colors'),
          ringOffsetWidth: {
            '0': '0px',
            '1': '1px',
            '2': '2px',
            '4': '4px',
            '8': '8px',
          },
          ringOpacity: (theme) => ({
            DEFAULT: '0.5',
            ...theme('opacity'),
          }),
          ringWidth: {
            '0': '0px',
            '1': '1px',
            '2': '2px',
            '4': '4px',
            '8': '8px',
            DEFAULT: '3px',
          },
          rotate: {
            '0': '0deg',
            '1': '1deg',
            '2': '2deg',
            '3': '3deg',
            '6': '6deg',
            '12': '12deg',
            '45': '45deg',
            '90': '90deg',
            '180': '180deg',
            '-180': '-180deg',
            '-90': '-90deg',
            '-45': '-45deg',
            '-12': '-12deg',
            '-6': '-6deg',
            '-3': '-3deg',
            '-2': '-2deg',
            '-1': '-1deg',
          },
          saturate: {
            '0': '0',
            '50': '.5',
            '100': '1',
            '150': '1.5',
            '200': '2',
          },
          scale: {
            '0': '0',
            '50': '.5',
            '75': '.75',
            '90': '.9',
            '95': '.95',
            '100': '1',
            '105': '1.05',
            '110': '1.1',
            '125': '1.25',
            '150': '1.5',
          },
          sepia: {
            '0': '0',
            DEFAULT: '100%',
          },
          skew: {
            '0': '0deg',
            '1': '1deg',
            '2': '2deg',
            '3': '3deg',
            '6': '6deg',
            '12': '12deg',
            '-12': '-12deg',
            '-6': '-6deg',
            '-3': '-3deg',
            '-2': '-2deg',
            '-1': '-1deg',
          },
          space: (theme, { negative }) => ({
            ...theme('spacing'),
            ...negative(theme('spacing')),
          }),
          stroke: {
            current: 'currentColor',
          },
          textColor: (theme) => ({
            ...theme('colors'),
            body: '#000',
          }),
          textOpacity: (theme) => theme('opacity'),
          transformOrigin: {
            center: 'center',
            top: 'top',
            'top-right': 'top right',
            right: 'right',
            'bottom-right': 'bottom right',
            bottom: 'bottom',
            'bottom-left': 'bottom left',
            left: 'left',
            'top-left': 'top left',
          },
          transitionDelay: {
            '75': '75ms',
            '100': '100ms',
            '150': '150ms',
            '200': '200ms',
            '300': '300ms',
            '500': '500ms',
            '700': '700ms',
            '1000': '1000ms',
          },
          transitionDuration: {
            '75': '75ms',
            '100': '100ms',
            '150': '150ms',
            '200': '200ms',
            '300': '300ms',
            '500': '500ms',
            '700': '700ms',
            '1000': '1000ms',
            DEFAULT: '150ms',
          },
          transitionProperty: {
            none: 'none',
            all: 'all',
            DEFAULT:
              'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
            colors: 'background-color, border-color, color, fill, stroke',
            opacity: 'opacity',
            shadow: 'box-shadow',
            transform: 'transform',
          },
          transitionTimingFunction: {
            DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
            linear: 'linear',
            in: 'cubic-bezier(0.4, 0, 1, 1)',
            out: 'cubic-bezier(0, 0, 0.2, 1)',
            'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
          },
          translate: (theme, { negative }) => ({
            ...theme('spacing'),
            ...negative(theme('spacing')),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            full: '100%',
            '-1/2': '-50%',
            '-1/3': '-33.333333%',
            '-2/3': '-66.666667%',
            '-1/4': '-25%',
            '-2/4': '-50%',
            '-3/4': '-75%',
            '-full': '-100%',
          }),
          width: (theme) => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.333333%',
            '2/3': '66.666667%',
            '1/4': '25%',
            '2/4': '50%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.666667%',
            '2/6': '33.333333%',
            '3/6': '50%',
            '4/6': '66.666667%',
            '5/6': '83.333333%',
            '1/12': '8.333333%',
            '2/12': '16.666667%',
            '3/12': '25%',
            '4/12': '33.333333%',
            '5/12': '41.666667%',
            '6/12': '50%',
            '7/12': '58.333333%',
            '8/12': '66.666667%',
            '9/12': '75%',
            '10/12': '83.333333%',
            '11/12': '91.666667%',
            full: '100%',
            screen: '100vw',
          }),
          zIndex: {
            '0': '0',
            '10': '10',
            '20': '20',
            '30': '30',
            '40': '40',
            '50': '50',
            auto: 'auto',
          },
        },
      },
    },
  ],
  theme: {
    extend: [],
  },
  content: [
    './src/pug/*.pug',
    './src/html/*.html',
    './src/pages/*.js',
    './src/components/*/*.js',
  ],
  plugins: [],
};

